spring:
  cloud:
    gateway:
      mvc:
        default-filters:
          - ResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods: "*"
        #                allowed-headers: "*"
        routes:
          - id: eventorg-event-service
            uri: lb://eventorg-event-service
            predicates:
              - Path=/api/events/**


          - id: eventorg-guest-service
            uri: lb://eventorg-guest-service
            predicates:
              - Path=/api/guest/**

          - id: eventorg-vendor-service
            uri: lb://eventorg-vendor-service
            predicates:
              - Path=/api/vendors/**

#          - id: user-service
#            uri: lb://user-service
#            predicates:
#              - Path=/api/users/**

          - id: eventorg-task-service
            uri: lb://eventorg-task-service
            predicates:
              - Path=/api/task/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
